version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    depends_on:
      openrgb:
        condition: service_started

  openrgb:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "6742:6742"
